version: "3.7"
services:
    nocode:
      image: node:20.11.1
      working_dir: /usr/src/app
      tty: true
      ports: 
      - '3005:3000'
      volumes:
        - ./:/usr/src/app
      command: >
        bash -c "npm install && npm run dev"